### ISSUE TITLE
Just trying to update an existing installation. Now it won't connect to postgres.

### ISSUE THREAD

**Issue by atljoseph** [plandex-ai/plandex#163] opened 2024-07-06 01:49 UTC
Did a git pull on the main branch. Didn't change anything. Still had ENV from before. Ran bash start_local.sh, and built fine. Now it says `pq: password authentication failed for user "root"`. Why would that change? I deleted the ~/.plandex-home dir, as well as /var/lib/plandex/data and /var/lib/postgresql/data. Same error before, same error after. Did i not delete all the things i should have? Is there an option to use a more portable database, like SQLite? And is there not an easier way to reset things? Looking for a stable upgrade path. I've hit this snag about deleting seemingly important directories and those actions not having any effects multiple times. Is there an easier way to accomplish a silky smooth upgrade path?

**Comment by danenania** [comment] 2024-07-09 16:22
There were some changes to the docker-compose config introduced in this commit: https://github.com/plandex-ai/plandex/commit/6e9dd6701e7b4eabfabd2335fc6e41aa1c42395f

@appreciated Any ideas?

**Comment by appreciated** [comment] 2024-07-09 21:05
@danenania The issue is probably that @atljoseph followed the self-hosting guide. 
I tried it myself and could not make it work on my machine.
This is due to an issue which I fixed with #168

**Comment by danenania** [comment] 2024-07-10 18:31
@appreciated @atljoseph  I'm working on a fix for this, and I'm also reworking the self-hosting guide as part of a new docs site. Should have it pushed up today/tomorrow and then hopefully we should be past the self-hosting issues for good :)

**Comment by danenania** [comment] 2024-07-11 18:54
This should now be fixed. @atljoseph could you please copy the latest `app/_env` into `app/.env` and try again?

**Closed by danenania** 2024-07-11 18:54 UTC
