### ISSUE TITLE
Can you provide me with a detailed operation manual, author? Why do I encounter errors after running it

### ISSUE THREAD

**Issue by yxl23** [plandex-ai/plandex#63] opened 2024-04-09 05:18 UTC
![image](https://github.com/plandex-ai/plandex/assets/115678682/05e9eb93-2902-408d-b713-79edff4d3fe7)

**Comment by Dexus** [comment] 2024-04-09 09:27
see #32 #53 #48 etc. all the same you openai account has no payment or reached the limits.

**Comment by danenania** [comment] 2024-04-09 15:58
Thanks @Dexus 

@yxl23 as @Dexus said, this is most likely caused by either an invalid OpenAI api key or not having OpenAI credits. This will be fixed in the next release.

Closing as a duplicate of #32.

**Closed** 2024-04-09 16:01 UTC
