### ISSUE TITLE
I'm not sure if this needs a new issue or not. I'll add it here and create a new one if you think it needs it.

### ISSUE THREAD

**Issue by Lucifertru86** [plandex-ai/plandex#55] opened 2024-04-08 10:44 UTC
I'm not sure if this needs a new issue or not. I'll add it here and create a new one if you think it needs it.

I noticed the path is not what I expected.
```
      → /root/plandex-server/orgs/0368f56f-0794-4a83-8324-0392b07e4338/plans/3b6546fe-6408-4d3b-bfa3-b62df1cb3d3f, err
```
Shouldn't this be `/plandex-server` not `/root/plandex-server`? I don't think this is how I'm building the image.
```
$ docker inspect --format='{{json .Mounts}}' app-plandex-server-1 | jq '.' ; sudo ls -l $HOME/projects/plandex-data/plandex-data
[
  {
    "Type": "bind",
    "Source": "/home/harleypig/projects/plandex-data/plandex-data",
    "Destination": "/plandex-server",
    "Mode": "rw",
    "RW": true,
    "Propagation": "rprivate"
  }
]
[sudo] password for harleypig: 
Executing: sudo ls -l /home/harleypig/projects/plandex-data/plandex-data 
total 0
```

_Originally posted by @harleypig in https://github.com/plandex-ai/plandex/issues/8#issuecomment-2030916651_hfta454ivfdzmokmoo09kmt7h। ****gyu
Kuy7o000796toonb
088yrwrt

**Comment by danenania** [comment] 2024-04-08 17:18
Hi @Lucifertru86 thanks for reporting! Yes this looks like a dupe of #9.

**Closed by danenania** 2024-04-08 17:18 UTC
