### ISSUE TITLE
Error getting plan, context, convo, or summaries

### ISSUE THREAD

**Issue by Dexus** [plandex-ai/plandex#32] opened 2024-04-05 14:29 UTC
```
$ plandex t --file promt/p1-golang.txt
✅ Context is up to date
� Server error
  → Error getting plan, context, convo, or summaries
```

using alpine linux

**Comment by danenania** [comment] 2024-04-05 16:44
Thanks for reporting @Dexus. I'll get this error message fixed

**Comment by viperfx** [comment] 2024-04-05 18:25
Seeing a similar issue. Is it seems like an issue with Plandex cloud?

**Comment by danenania** [comment] 2024-04-05 18:36
@viperfx The underlying error message isn't getting through (I'm working on a fix for that), but is most commonly a 401 from OpenAI when an API key is invalid or out of credits.

**Comment by urstrulysv** [comment] 2024-04-07 17:02
Confirmed, @danenania  The issue is indeed attributable to insufficient API credits. I trust this information will be instrumental in resolving the code

**Comment by burkayedu** [comment] 2024-04-07 17:20
same issue on wsl

**Closed** 2024-04-09 19:28 UTC
