### ISSUE TITLE
baseUrl config

### ISSUE THREAD

**Issue by bracebrace008** [plandex-ai/plandex#61] opened 2024-04-09 02:28 UTC
in openai I can config baseUrl, is it ok to config here?

**Comment by paradise321** [comment] 2024-04-09 13:37
Better to add Base URL configuration, thanks!

**Comment by paradise321** [comment] 2024-04-09 13:59
Better to add Base URL configuration, thanks!

**Comment by danenania** [comment] 2024-04-09 16:02
Duplicate of #16. This will be included in the next release.

**Closed** 2024-04-09 16:02 UTC
